"""Add generation_method to ContextEntry

Revision ID: 7dd91f3b867a
Revises: 683bd4dd3c35
Create Date: 2024-07-25 10:52:31.247827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd91f3b867a'
down_revision = '683bd4dd3c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('context_entry', sa.Column('generation_method', sa.String(length=50), nullable=True))
    op.execute("UPDATE context_entry SET generation_method='gemini'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('context_entry', 'generation_method')
    # ### end Alembic commands ###

